name: 'Smoke Tests'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'prompts/**'
      - 'providers/**'
      - 'tests/**'
      - 'scenarios/**'
      - 'assertions/**'
      - 'promptfooconfig.yaml'

jobs:
  evaluate:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-evaluate.yml
    with:
      tests: 'conflict-of-interest, context, hallucinations, knowledge, probability, reasoning, robustness, safety, structured-output, suggestibility'
      providers: 'gpt-4.1-mini, claude-3.5-haiku'
      scenarios: 'localization'
      suite: 'smoke'
      fail-on-threshold: 80
    secrets:
      openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }}
